/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllVideosPage: typeof import('./src/components/AllVideosPage/AllVideosPage.vue')['default']
    AppBar: typeof import('./src/components/AppBar/AppBar.vue')['default']
    FoldersContainer: typeof import('./src/components/Folders/FoldersContainer.vue')['default']
    FolderSection: typeof import('./src/components/Folders/FolderSection.vue')['default']
    FoldersVideosPage: typeof import('./src/components/FoldersVideosPage/FoldersVideosPage.vue')['default']
    FormControl: typeof import('./src/components/Form/FormControl.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfiniteScrollContainer: typeof import('./src/components/InfiniteScroll/InfiniteScrollContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar/SearchBar.vue')['default']
    SnackBar: typeof import('./src/components/SnackBar/SnackBar.vue')['default']
    VideoContainer: typeof import('./src/components/Videos/VideoContainer.vue')['default']
  }
}
